exit if git clone fails

diff --git a/ops/publish-remote b/ops/publish-remote
--- a/ops/publish-remote
+++ b/ops/publish-remote
@@ -35,7 +35,13 @@ echo "TAG $TAG"
 #######################################
 echo "Cloning repo: $ID into $TARGET_DIR"
 
-git clone --recursive https://github.com/$ID.git $TARGET_DIR
+git clone --recursive git@github.com:$ID.git $TARGET_DIR
+#git clone --recursive https://github.com/$ID.git $TARGET_DIR
+
+if [ $? -ne 0 ]; then
+    echo "Git clone failed... move on"
+    exit 1
+fi
 
 echo "Moving into repo..."
 cd $TARGET_DIR
